### ISSUE TITLE
to support many concurrent users

### ISSUE THREAD

**Issue by YunzhaoLu** [alumae/kaldi-gstreamer-server#100]
Is there an easy way to support many concurrent users with kaldi-gstreamer?.
Basically, I can start around 10 workers at one vm, but how about to support 100 concurrent users?
Your advice is highly appreciated.

Luke

**Comment by alumae** [comment]
The workers do not have to be on the same machine as the server. So, just add 10 more VMs with 10 workers, each connecting to the same server.
