### ISSUE TITLE
problem encountered on the 8k model

### ISSUE THREAD

**Issue by dijiagui** [alumae/kaldi-gstreamer-server#115]
Hi,
I am new to kaldi.
I used to use 16k wav to trained my model, everything did ok . But now I trained my model with 8K wav,and modify sample-frequency in mfcc config to 8000, use nnet3 online decoder, then I can get a true result but only a half, the segment-length is always half of total-length in the result. If I do not send EOF but then send something else like other audio stream, I can get the rest of the results. Is there something I did not notice in the config?

**Comment by alumae** [comment]
I am not able to reproduce the problem with a 8k nnet2 model (fisher). Can you give a bit more information what are you trying to do? It would be great if you could provide model files, a conf file and a test audio file. 

You shouldn't have to configure anything in the kaldi-gstreamer-server conf file to use 8k models -- the server should automatically use the correct sample rate of the model.

**Comment by dijiagui** [comment]
I get everything OK when I use 'sed -i "s#samp_freq(16000),#samp_freq(8000),#g" kaldi/src/feat/pitch-functions.h' ,and then make install kaldi again. Thank you for your time.
