### ISSUE TITLE
Provide the `request_id` to the full_post_processor script

### ISSUE THREAD

**Issue by disooqi** [alumae/kaldi-gstreamer-server#123]
I want to use the full_post_processor script to process the raw audio that you save when worker accept a connection from the client. However the passed JSON does not contain the id. Would you add the request_id to the json before sending it to the full_post_processor so I can find the right raw audio file you save by the worker?

P.S. I could do that if you accept my pull request.

Thank you very much

Mohamed Eldesouki, QCRI

**Comment by alumae** [comment]
Merged, thanks!
