### ISSUE TITLE
ImportError: No module named repository

### ISSUE THREAD

**Issue by mosherayman** [alumae/kaldi-gstreamer-server#13]
I get the following error when i try to start the sample worker

moshe@cloud-server-04:~/kaldi-gstreamer-server/trunk$ uname -a
Linux cloud-server-04 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux
moshe@cloud-server-04:~/kaldi-gstreamer-server/trunk$ python kaldigstserver/worker.py -u ws://localhost:8888/worker/ws/speech -c sample_worker.yaml
Traceback (most recent call last):
  File "kaldigstserver/worker.py", line 9, in <module>
    from gi.repository import GObject
ImportError: No module named repository

thanks

**Comment by alumae** [comment]
Try installing the python-gi package, let me know if it helps.

**Comment by mosherayman** [comment]
Did that and reinstalled it as well

============
thanks,
Moshe

**Comment by alumae** [comment]
So it works for you now?

**Comment by mosherayman** [comment]
No, same error

============
thanks,
Moshe

**Comment by alumae** [comment]
Try installing the package `python-gobject`, if not already installed.

**Comment by mosherayman** [comment]
no luck, already installed

**Comment by alumae** [comment]
Do you have many versions of python installed? What is the output of command `which python`?

**Comment by mosherayman** [comment]
i am new to python, and decided that I must have messed up the install

so I started form scratch, and now the onlinegmmdecodefaster is working,
thanks for your help and patients

all I needed to do is apt-get install python-gi

and I see that is in the README

just a few comments, you should mention in your README.md that when
compiling kaldi, you should use the --shared flag in configure.

Also to install ws4py
pip install ws4py==3.2.0
does not work

it should be
pip install ws4py==0.3.2
