### ISSUE TITLE
Return the recognize result of every word.

### ISSUE THREAD

**Issue by vzxxbacq** [alumae/kaldi-gstreamer-server#143]
Hello @alumae , thanks for your great work.
I'm using your code to build an online decoding asr server, but I found it only return the best result of every sentence.
What should I do if i want to know the result of every second even if the result isn't the best.

**Comment by alumae** [comment]
Use the websocket based server API. See client.py.

**Comment by vzxxbacq** [comment]
Just need to override received_message.

Thank you, alumae.
