### ISSUE TITLE
could i used the DFSMN language model to provide the service

### ISSUE THREAD

**Issue by AlexPeng19** [alumae/kaldi-gstreamer-server#146]
Dear Tanel :
    You know the alibaba/Alibaba-MIT-Speech project on github used the DFSMN language model based on KALDI project, which improved the Speech recognition recognition rate into 96%. so i have trained the language model, could i know is it compatible for our project to provide service based on that model.  if it is, what changes should i made. @alumae 
    Looking forward  your response.

**Comment by alumae** [comment]
I am afraid kaldi-gstreamer-server is not compatible with the Alibaba models as it requires heavy patching of Kaldi.
