### ISSUE TITLE
Invalid parameters supplied to OnlineLdaInput

### ISSUE THREAD

**Issue by fancyerii** [alumae/kaldi-gstreamer-server#147]
I trained the model by the recipe in the kaldi/egs/thchs30/s5
After training, I want to use kaldi-gstreamer-server to  provide decoding service.
my yaml is configed as:
timeout-decoder : 10
decoder:
   model: test/models/thchs30/tri4b/final.mdl
   lda-mat: test/models/thchs30/tri4b/final.mat
   word-syms: test/models/thchs30/tri4b/words.txt
   fst: test/models/thchs30/tri4b/HCLG.fst
   silence-phones: "1"
out-dir: tmp

When I run python kaldigstserver/client.py -r 32000 test/data/D21_848.wav 
The worker print error messages and exit abnormally.

ERROR ([5.4.232-532f3]:OnlineLdaInput():online-feat-input.cc:209) Invalid parameters supplied to OnlineLdaInput

[ Stack-Trace: ]

kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::OnlineLdaInput::OnlineLdaInput(kaldi::OnlineFeatInputItf*, kaldi::Matrix<float> const&, int, int)

clone

terminate called after throwing an instance of 'std::runtime_error'
  what():

**Comment by alumae** [comment]
Probably you are using pitch features, and the GMM-based decoder doesn't support pitch. Use nnet3-based model, then you can use pitch features.
