### ISSUE TITLE
how to configure online dictation with microphone

### ISSUE THREAD

**Issue by AlexPeng19** [alumae/kaldi-gstreamer-server#148]
i noticed the demo http://bark.phon.ioc.ee/dictate/ could get audio from microphone, but current README only showed the recognization by sending audio file. which api could i use to get that.

by the way i am using https://kaljurand.github.io/dictate.js, i want to replace wss://bark.phon.ioc.ee with my service.

looking forward your response.

**Comment by visi0nary** [comment]
Have you seen this?

`

2017-06-28: The sample client program can now accept audio from stdin. This can be used to test the server with a live microphone, e.g.: arecord -f S16_LE -r 16000 | python kaldigstserver/client.py -r 32000 -. Thanks to @wkuna!

`

**Comment by alumae** [comment]
It should be resolved? Reopen if there is still a problem.

**Comment by boleamol** [comment]
I am trying to use with live microphone using following command

_arecord -f S16_LE -r 16000 | python kaldigstserver/client.py -r 32000_

but getting following error..

_usage: client.py [-h] [-u URI] [-r RATE]
                 [--save-adaptation-state SAVE_ADAPTATION_STATE]
                 [--send-adaptation-state SEND_ADAPTATION_STATE]
                 [--content-type CONTENT_TYPE]
                 audiofile
client.py: error: too few arguments
Recording WAVE 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono_

**Comment by alumae** [comment]
You are missing "-" at the end of the command.

**Comment by boleamol** [comment]
Thanks Its working perfectly..
If I want to use my acoustic then which model I have to train?
like tri2b, tri2b_mmi.. if neural network then which NN like nnet1, nnet2, nnet3... If possible tell me example in kaldi/egs..
Thank you in advance..

**Comment by alumae** [comment]
The tool supports trigram models (with no SAT), nnet2 models and nnet3 models. I recommend to use chain TDNN models.

**Comment by boleamol** [comment]
Silly question but sorry...

How to use chain TDNN model ? means where I have to do changes?

**Comment by maitrungduc1410** [comment]
[Here](https://gist.github.com/maitrungduc1410/fa9a5994a6400fbccfc517b53d0915b2) I have complete and working code for decoding from microphone, python 2 and 3 are supported. Hope this help someone
