### ISSUE TITLE
re: Confidence scores

### ISSUE THREAD

**Issue by rohithkodali** [alumae/kaldi-gstreamer-server#16]
HI alumae,

```
           thank a ton for the project you have created, i have started using it from a couple of weeks. i struck at getting confidence scores,  how can i get confidence scores for every word in the json file.
```

**Comment by alumae** [comment]
Confidence scores are not yet implemented.

**Comment by meitals** [comment]
Any plans to implement this soon? Or suggestions on how to go about implementing it?
Thanks a lot!

**Comment by alumae** [comment]
Currently there are no plans to implement this.

**Comment by alumae** [comment]
Implemented in gst-kaldi-nnet2-online. Set the `do-word-confidences=true` and also set
the `word-boundary-file=dir/word_boundary.int`, since the word confidences will be included
with the word alignment information

**Comment by alumae** [comment]
I decided to remove the do-word-confidences property: word confidences are now always generated for all word alignments.
