### ISSUE TITLE
Your GStreamer installation is missing a plug-in

### ISSUE THREAD

**Issue by wblgers** [alumae/kaldi-gstreamer-server#175]
Hi,

I meet this error if I try to decode a encoder audio file rather than the raw audio file. Can you give me some suggestions?
PS: I've already installed the plugins of gstreamer 1.0 via this command:
sudo apt-get install gstreamer1.0-plugins-bad  gstreamer1.0-plugins-base gstreamer1.0-plugins-good  gstreamer1.0-pulseaudio  gstreamer1.0-plugins-ugly  gstreamer1.0-tools libgstreamer1.0-dev

Best,
Wen Bolong

**Comment by bliunlpr** [comment]
I have met the same error. Any ideas to solve it? Thanks!

**Comment by wblgers** [comment]
> I have met the same error. Any ideas to solve it? Thanks!

It seems that adding the gstreamer0.1 will solve this issue. You can try it
