### ISSUE TITLE
is there any java client api for real time speech dictation

### ISSUE THREAD

**Issue by badboys4life007** [alumae/kaldi-gstreamer-server#19]
Helllo i found there in readme file that Python, Java, Javascript clients are available on kaldi-gstreamer-server. i did not find java client sample code anywhere... is there available for real time dictation demo?

**Comment by alumae** [comment]
Yes, there is a Java library that contains the client API: https://github.com/Kaljurand/net-speech-api/tree/master/src/main/java/ee/ioc/phon/netspeechapi/duplex

There is an Android app Kõnele that contains a client implementation, check https://github.com/Kaljurand/K6nele/blob/master/app/src/ee/ioc/phon/android/speak/WebSocketRecognizer.java

**Comment by Kaljurand** [comment]
The client in Kõnele has moved to https://github.com/Kaljurand/K6nele/tree/master/app/src/ee/ioc/phon/android/speak/service

**Comment by Umar17** [comment]
Dear All,
I have successfully used this code for audio files. Now, I want to modify api for live mic streaming. Objective is to capture mic and decoding it online. Is there any api for that?
I have captured mic and converting it into bytes array. This byte array is being passed to modified sendFile function (modify to get byte array chunk as argument). But Gstreamer, in this case, raises "Could not determine type of stream." or "Your Gstreamer installation missing plugin" error.
Please guide

Best Regards

**Comment by maitrungduc1410** [comment]
@Umar17 ,
[Here](https://gist.github.com/maitrungduc1410/fa9a5994a6400fbccfc517b53d0915b2) I have complete and working code for decoding from microphone, python 2 and 3 are supported
