### ISSUE TITLE
How to pass lattice / phrase hints to kaldi to decode at the time of sending data?

### ISSUE THREAD

**Issue by axchanda** [alumae/kaldi-gstreamer-server#194]
I want to send data into the Kaldi decoder while passing speech data along with the other lattices/ phrase hints so that it can give more prefernece for the mentioned word while decoding. 
For reference, please see https://cloud.google.com/speech-to-text/docs/basics#phrase-hints

**Comment by alumae** [comment]
This is not possible at the moment and there are no plans to implement this.
