### ISSUE TITLE
error occurs on server log when trying to send chunk using java client api

### ISSUE THREAD

**Issue by badboys4life007** [alumae/kaldi-gstreamer-server#20]
hello, i refer you java client application to send audio file for transcription. on server side log, it print below log file on it..

 INFO 2015-07-04 18:16:23,776 New worker available <__main__.WorkerSocketHandler object at 0x7f67300b8c10> 
   ERROR 2015-07-04 18:16:27,708 Uncaught exception in /worker/ws/speech 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 415, in _run_callback
    callback(*args, **kwargs)
  File "kaldigstserver/master_server.py", line 260, in on_message
    assert self.client_socket is not None
AssertionError
    INFO 2015-07-04 18:16:27,709 Worker <__main__.WorkerSocketHandler object at 0x7f67300b8c10> leaving

**Comment by alumae** [comment]
Could you give a minimal Java client code that causes this? Thanks a lot!

**Comment by badboys4life007** [comment]
hello just i got d problem, i was passing sockets on wrong url... sorry for that
