### ISSUE TITLE
Decode result different from online2-wav-nnet3-latgen-faster

### ISSUE THREAD

**Issue by kli017** [alumae/kaldi-gstreamer-server#229]
Hi I was able to implement the gstkaldi decoder successfullly. I have train a chain model on my own data and modified the yaml according to the sample_chinese_nnet3.yaml. However, I found that the decode result was slightly differernt from the online decoder in kaldi onlie2bin. Some words get wrong while the online2-wav-nnet3-latgent-faster was correct. Is there anything wrong with my config or any other reason?

**Comment by YichiHuang** [comment]
I got the same problem, any solution got?

**Comment by kli017** [comment]
no solution yet. seems this decoder is based on online2-wav-nnet2
