### ISSUE TITLE
Retrieving word level time stamp

### ISSUE THREAD

**Issue by shaheenkdr** [alumae/kaldi-gstreamer-server#234]
Is there a way we could retrieve the world level timestamps along with the output?

**Comment by alumae** [comment]
Set the property word-boundary-file=dir/word_boundary.int (under the decoder conf), this activates word alignment generation.

**Comment by shaheenkdr** [comment]
Thanks @alumae , I can see the output in `worker.log` . However which endpoint passes that output back to the client ? Couldnt see it from Python client as well as curl . Would be helpful if you could share some pointers in that regard : /

**Comment by alumae** [comment]
It is passed in the JSON representation that the client receives from the server.

**Comment by shaheenkdr** [comment]
both in the websocket as well as the dynamic recognize http end points ?

**Comment by aish3155** [comment]
> Thanks @alumae , I can see the output in `worker.log` . However which endpoint passes that output back to the client ? Couldnt see it from Python client as well as curl . Would be helpful if you could share some pointers in that regard : /

Hey, can you let me know the location of this 'worker.log' file and also in which script you made the changes to see the required output?
