### ISSUE TITLE
single word audio file gives multiple results, how to choose the correct result?

### ISSUE THREAD

**Issue by ajaysg** [alumae/kaldi-gstreamer-server#240]
for example in the screenshot,
![Screenshot from 2020-06-03 23-06-40](https://user-images.githubusercontent.com/22977639/83671669-b4ab1100-a5f2-11ea-882a-82baeed819fd.png)
 when i test the audio file containing the word `replace`, i am getting multiple results, but at some point of time the decoder gives `replace`. How to print the correct result?

**Comment by alumae** [comment]
The lines before the last one represent intermediate results. The last line is the final result. You should study the client.py source code, it's not that difficult.
