### ISSUE TITLE
adding extra parameters

### ISSUE THREAD

**Issue by rohithkodali** [alumae/kaldi-gstreamer-server#27]
Hi Tanel,

   Is there anyway that we can send some extra parameters using curl 
ex: using a particular language model for some specific speakers etc based on some speaker ID and language model name sent to server.

**Comment by alumae** [comment]
Such functionality is not implemented. But it shouldn't be too difficult to add this: the nnet2-based GStreamer plugin allows changing the HCLG.fst on the fly, you just have to hack some python in worker.py and decoder2.py.

I'm afraid it will be very application specific, so I don't really want to add this to the main branch (unless of course you propose a very elegant solution).

**Comment by rohithkodali** [comment]
Is the hclg.fst changing on the fly is added anywhere ?

**Comment by alumae** [comment]
I don't understand your question.

**Comment by rohithkodali** [comment]
In previous mail you mentioned that  gstreamer allows to change hclg.fst on
the fly

My question is that is these feature implemented anywhere in code

**Comment by alumae** [comment]
The nnet2 GStreamer plugin has a 'fst' property that is currently set once via the conf file. However, you could change this property via python between individual requests. 
If you are asking whether there is a sample available on how to do this, then no, I don't think so.
