### ISSUE TITLE
Final Transcript have segment number missing

### ISSUE THREAD

**Issue by ngoel17** [alumae/kaldi-gstreamer-server#31]
Since the creation of JSON for final was moved to the plugin, it is missing the segment number, while the partial transcripts contain the segment number. This is a little confusing, and probably the we would need to keep two separate counters so that both have segment numbers. Maybe move the partial creation also to the plugin.

**Comment by alumae** [comment]
I fixed it by adding the segment nr to the final JSON inside the worker.
