### ISSUE TITLE
converting saved raw files into wav

### ISSUE THREAD

**Issue by rohithkodali** [alumae/kaldi-gstreamer-server#40]
hi tanel,

What is the format of the raw files that are saved using gstreamer, is there anyway to convert them into wav files?

**Comment by alumae** [comment]
The format is 16 kHz, 16 bit, signed, mono. This sox comman line should work:

    sox -r 16000 -e signed-integer -b 16 -c 1 input.raw output.wav

**Comment by rohithkodali** [comment]
i have tried it but the output is playing 4 times faster

ex: 1 minute audio file is converted into 15 seconds 

[45.wav.zip](https://github.com/alumae/kaldi-gstreamer-server/files/183415/45.wav.zip)
