### ISSUE TITLE
online demon does not work

### ISSUE THREAD

**Issue by SamyCookie** [alumae/kaldi-gstreamer-server#43]
Hi,

Online demo does not work on my computer. Microphone does not seem to be detected, and nothing happens.
Please fix the issue :)

Thanks, Samuel

**Comment by alumae** [comment]
Fixed. I recently moved to https/wss and forgot to update some URLs in the demo javascript code.

**Comment by SamyCookie** [comment]
It works, thanks a lot !

**Comment by maitrungduc1410** [comment]
[Here](https://gist.github.com/maitrungduc1410/fa9a5994a6400fbccfc517b53d0915b2) I have complete and working code for decoding from microphone, python 2 and 3 are supported. Hope this help someone
