### ISSUE TITLE
Online dictation with Microphone

### ISSUE THREAD

**Issue by MatteoBotta** [alumae/kaldi-gstreamer-server#44]
I work with kaldo-gstreamer-server and system transcribes correctly with different  input file.

Now I could  try to transcribe in online mode.
Is it possible active the streaming audio with microphone in client.py script.
For example like the script run_gui.py in voxforge/gst_demo
Thanks in Advance 

Matteo

**Comment by skoocda** [comment]
Hi Matteo,

Have you tried [Dictate.JS](https://github.com/Kaljurand/dictate.js) ?

It's probably your best bet, just point it at your locally hosted Kaldi Gstreamer websocket location and then you can stream audio easily through a browser.

**Comment by alumae** [comment]
The client.py program can now accept microphone audio, see a notice at the beginning of the README.

**Comment by shaheenkdr** [comment]
@alumae Can we pipe the audio using `rec` to the python client or to the JS client ? Some insights on that would be immensely helpful. Thanks

**Comment by alumae** [comment]
Yes, you can pipe audio to python client like this:
arecord -f S16_LE -r 16000 | python kaldigstserver/client.py -r 32000 -

**Comment by shaheenkdr** [comment]
@alumae Cool , thanks ! Also what would be the ideal way to pass RTMP streams to the client? Is it supported

**Comment by alumae** [comment]
Sorry, you have to figure this out yourself.

**Comment by maitrungduc1410** [comment]
[Here](https://gist.github.com/maitrungduc1410/fa9a5994a6400fbccfc517b53d0915b2) I have complete and working code for decoding from microphone, python 2 and 3 are supported. Hope this help someone
