### ISSUE TITLE
Concept of kaldi-gstreamer-server

### ISSUE THREAD

**Issue by chlo41** [alumae/kaldi-gstreamer-server#50]
Hi Sirs,

I am the beginner for kaldi.
I am a little confusing on kaldi-gstreamer-server recently.
After I generate models and others...
1. What is the next step I need to do? Apply to kaldi-gstreamer-server (via yaml file)?
2. If the server could be created by myself? Or I should use this one?
3. The relationship between kaldi models and gstreamer-server?
4. Any information I can reference if I want to know "how to apply kaldi models into server"?

Maybe my concepts about kaldi-gstreamer-server are not correct, please give me some suggestions or information please. Thanks very much.

**Comment by alumae** [comment]
kaldi-gstreamer-server is software meant for hosting Kaldi models on your own server.
