### ISSUE TITLE
How to write a suitable YAML file before applying to server?

### ISSUE THREAD

**Issue by chlo41** [alumae/kaldi-gstreamer-server#51]
Hi Sirs,

May I know how to write a proper YAML file?
I don't think YAML files are all the same for every kaldi models.
Any information or document I can find about "writing my YAML file"?
Thanks for your kindly support...

**Comment by alumae** [comment]
To see available properties for a nnet2 model, invoke

    GST_PLUGIN_PATH=<path to kaldinnet2onlinedecoder>  gst-inspect-1.0 kaldinnet2onlinedecoder

as described here: https://github.com/alumae/gst-kaldi-nnet2-online
