### ISSUE TITLE
segment-length and word timings off in nnet3

### ISSUE THREAD

**Issue by russlevy** [alumae/kaldi-gstreamer-server#62]
I noticed that the subsampling issue was already fixed in kaldi
https://github.com/kaldi-asr/kaldi/issues/1184 by @alumae 
However, after recompiling kaldi and gst-kaldi-nnet2-online everything seems to be off a factor of the subsampling size. Is there another change that needs to be made?

**Comment by russlevy** [comment]
This is an issue in gst-kaldi-nnet2-online, not here... Can be closed when that is merged in (or before).

**Comment by alumae** [comment]
Fixed now in gst-kaldi-nnet2-online.
