### ISSUE TITLE
Segmentation

### ISSUE THREAD

**Issue by ersigcha23** [alumae/kaldi-gstreamer-server#63]
Hi

I want to know how can I use the segmentation feature?

Thanks

**Comment by alumae** [comment]
Read https://github.com/alumae/gst-kaldi-nnet2-online:

> Full results can now inlude word alignment information for the best hypothesis. In order to activate this, set the word-boundary-file property to point to the word_boundary.int file typically found in the data/lang/phones/ subdirectory of a trained system.
