### ISSUE TITLE
Is there any solution for the low quality audio?

### ISSUE THREAD

**Issue by wang850228803** [alumae/kaldi-gstreamer-server#65]
Is there any solution for the low quality audio?

**Comment by nshmyrev** [comment]
Sure

1) Try to improve the quality of the audio. Think about better microphones, less lossy encoding-decoding, closer microphone
2) Train better acoustic models

This is not really a question about a server

**Comment by alumae** [comment]
Try training your acoustic models using reverbareted and noised training data. But yes, it's not a question about the server.
