### ISSUE TITLE
byterate for wav 44100 sample rate 1 channel

### ISSUE THREAD

**Issue by ersigcha23** [alumae/kaldi-gstreamer-server#66]
Hi 

I want to know what -r parameter I should put for wav 44100 16 bits 1 channel audio?

Thanks

**Comment by alumae** [comment]
16 bits is two bytes, so the appropriate value is 2*44100=88200.

**Comment by ersigcha23** [comment]
Thanks for answering

I already tried with 88200 but i guess that due to the gst-plugin limit of 16000 khz and 16 bit I'm receiving the 44100 wav file in raw format at 16000 and getting different results from those that i got when I used decode.sh of kaldi
Is there any solution for this or I have to train a new 16khz acoustic model instead of the 44.1khz model that i have?

Thanks
