### ISSUE TITLE
Audio capture problem

### ISSUE THREAD

**Issue by bchinnari** [alumae/kaldi-gstreamer-server#69]
Hi all

We have configured kaldi gstreamer as per the instructions. We are using kaljurand client package (as mentioned in your readme.md). After this whole setup, when we are trying to record the audio...server/worker is getting request from the client but the raw data which is stored in the tmp folder is empty (0 bytes) and the opened session is idle forever . Kindly let me know where it can go wrong.

Thanks
Bhargav

**Comment by alumae** [comment]
Are you using HTTPS? Newer Chrome versions don't allow recording audio if the page is served over HTTP.

**Comment by bchinnari** [comment]
We are using firefox.

**Comment by alumae** [comment]
Is there anything printed to the Firefox Javascript console? Try alos with Chrome and check the JS console.

**Comment by bchinnari** [comment]
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[Learn More]  jquery-1.10.2.min.js:1
navigator.mozGetUserMedia has been replaced by navigator.mediaDevices.getUserMedia  dictate.js:113:4
**SecurityError: Failed to load worker script at "/home/aai/Downloads/Kaljurand-dictate.js-7efd3b1/lib/recorderWorker.js"  (unknown)**
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  demo.html

This is the console log we are getting.

**Comment by alumae** [comment]
Does it work with Chrome?

**Comment by bchinnari** [comment]
No. Same error. We checked the path /home/aai/Downloads/Kaljurand-dictate.js-7efd3b1/lib/recorderWorker.js also. This is the correct path.

**Comment by bchinnari** [comment]
Launching chrome as follows 
"google-chrome --allow-file-access-from-files" and then opening demo.html cleared the error. It was working.

**Comment by bchinnari** [comment]
Hi Tanel,

I have a small question. In the current configuration, we can pre-define number of workers we want to run.  **Is it possible to launch and close a worker when a new status listener comes and leaves?**

**Comment by alumae** [comment]
No, there is no such possibility.

**Comment by bchinnari** [comment]
With small hack, we are able to launch the worker when status listener arrives. But we are not able close the worker when listener leaves.  Could you help in this.

The hack is one statement 

class StatusSocketHandler(tornado.websocket.WebSocketHandler):
    
    def check_origin(self, origin):
        return True
    def open(self):
        logging.info("New status listener")
        **os.system("supervisord -c /home/aai/supervisord_1worker.conf")**
        self.application.status_listeners.add(self)
        self.application.send_status_update_single(self)

**Comment by alumae** [comment]
Sorry, you are on your own with this.

**Comment by bchinnari** [comment]
I would like to know if it is possible at all
