### ISSUE TITLE
SSL websocket connection

### ISSUE THREAD

**Issue by lucgeo** [alumae/kaldi-gstreamer-server#71]
Hi,

I installed Kaldi Gstreamer Server and Kaljurand dictate.js client and it works ok only on Firefox without the SSL certificate. Then I installed a certificate on my machine and I modified on the client side the demos/demo.js and lib/dictate.js files, replacing ws://... with wss://... in SERVER and SERVER_STATUS variables.
Now, when I access https://my_host/demo.html page, it asks me to share the microphone, but it seems to do nothing when I press "Start" button. Looking into console I noticed the following message: "WebSocket connection to 'wss://my_host/client/ws/speech?content-type=a…string)interleaved,+rate=(int)16000,+format=(string)S16LE,+channels=(int)1' failed: WebSocket is closed before the connection is established" and after a while it appears "failed: WebSocket opening handshake timed out".
I would be grateful if you could give me a hint about how to configure the app to work using ssl. 

Thanks.

**Comment by lucgeo** [comment]
I solved the issue described above. As I said, on the client side I replaced ws:// with wss:// in SERVER and SERVER_STATUS variables (demo.js file). On the server side, I started the master server using the certfile and keyfile arguments and also I used wss:// instead of ws:// in the worker starting command. Now it works.

**Comment by sirifarif** [comment]
Hi, I am exactly the same problem, Is there any way to check this server with dummy certificates or something. In order to make sure that everything is OK with  the server.
Thanks

**Comment by purijs** [comment]
> I solved the issue described above. As I said, on the client side I replaced ws:// with wss:// in SERVER and SERVER_STATUS variables (demo.js file). On the server side, I started the master server using the certfile and keyfile arguments and also I used wss:// instead of ws:// in the worker starting command. Now it works.

Can you share what SSL/cert file you used and where you added those args? Also did you start with wss://localhost

**Comment by sirifarif** [comment]
@purijs When you start the server, use certificate file and key something like: 
```
master_server.py --port=xxxx --certfile=certifcate.crt --keyfile=certificate-key.key
```
And yes, after doing it, one has to use ```wss://localhost``` to access the server.

**Comment by maitrungduc1410** [comment]
The easiest when running in production is put your server after a Proxy (nginx) then install SSL on the Proxy (very easy with Certbot). After that you can connect to your server using `wss` without config and generate certificate yourself, which probably cause Error when a client connect to your server from browser as your certificate is not trusted
