### ISSUE TITLE
Unable to use gsteramer-server with opus codec

### ISSUE THREAD

**Issue by Habush** [alumae/kaldi-gstreamer-server#73]
I'm using Kaldi-gstreamer-server for live speech recognition app. When I send raw audio from the microphone it works perfectly. However, to reduce bandwidth usage, I am trying to encode it using [opus codec](http://opus-codec.org/) and decode it the server side. Hence I try to set the content-type query parameter of the url using the gstreamer capabilities of the opus decoder element. Although the opus gstreamer plugin is installed on the server, I get an error while the decoder tries to build the pipeline.

Here is the content-type parameter 

> audio/x-opus, channel-mapping-family=(int)[ 1, 255 ], channels=(int)[ 1, 255 ], stream-count=(int)[ 1, 255 ], coupled-count=(int)[ 0, 255 ]

I set the capabilities format from referring this [link](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-opusenc.html). 

I get the following error in the worker.log file

> 2017-03-15 13:53:26 -    INFO:   decoder2: 0578f66f-8474-48db-996b-ce401ed5c034: Setting caps to audio/x-opus, channel-mapping-family=(int)[ 1, 255 ], channels=(int)[ 1, 255 ], stream-count=(int)[ 1, 255 ], coupled-count=(int)[ 0, 255 ]
> 
> (python:1145): GStreamer-CRITICAL **: gst_event_new_caps: assertion 'gst_caps_is_fixed (caps)' failed
> 
> (python:1145): GStreamer-CRITICAL **: gst_pad_push_event: assertion 'GST_IS_EVENT (event)' failed
> 2017-03-15 13:53:27 -   ERROR:   decoder2: (GLib.Error('Internal data flow error.', 'gst-stream-error-quark', 1), 'gstbasesrc.c(2933): gst_base_src_loop (): /GstPipeline:pipeline0/GstAppSrc:appsrc:\nstreaming task paused, reason not-negotiated (-4)')
> 2017-03-15 13:53:27 -    INFO:   decoder2: 0578f66f-8474-48db-996b-ce401ed5c034: Resetting decoder state
> 
> (python:1145): GStreamer-CRITICAL **: gst_event_new_caps: assertion 'gst_caps_is_fixed (caps)' failed
> 
> (python:1145): GStreamer-CRITICAL **: gst_pad_push_event: assertion 'GST_IS_EVENT (event)' failed
> 
> (python:1145): GStreamer-CRITICAL **: gst_event_new_caps: assertion 'gst_caps_is_fixed (caps)' failed
> 
> (python:1145): GStreamer-CRITICAL **: gst_pad_push_event: assertion 'GST_IS_EVENT (event)' failed
> 2017-03-15 13:53:27 -   ERROR:   decoder2: (GLib.Error('Internal data flow error.', 'gst-stream-error-quark', 1), 'gstbasesrc.c(2933): gst_base_src_loop (): /GstPipeline:pipeline0/GstAppSrc:appsrc:\nstreaming task paused, reason not-negotiated (-4)')

What could be going here? How can I set the content-type query parameter so that I can use the opus codec?

I have uploaded both the master and worker logs so that they may provide more info.
[master.log.txt](https://github.com/alumae/kaldi-gstreamer-server/files/844780/master.log.txt)
[worker.log.txt](https://github.com/alumae/kaldi-gstreamer-server/files/844781/worker.log.txt)

**Comment by alumae** [comment]
A quick test showed to me that it works if the Opus audio is contained in an ogg file. I made such file using `ffmpeg -i test.ogg test.opus`. Then it works without specifying any content-type parameter.

It should also work if sending raw opus (without the ogg container), but I currently don't know how. So, just letting you know that it should work with the ogg container.

**Comment by alumae** [comment]
After getting a bit more familiar with Opus documentation, it seems that using an Ogg container with Opus codec is the standard way to do it. Even Opus native opusenc tool wraps a live stream to Ogg container. Does it work for you if you record a live stream from mic (hit Ctrl-C after sying something):
    
    arecord -c 2 -r 48000 -twav - | opusenc --bitrate 96 - - > stream.opus

And then:

    python kaldigstserver/client.py stream.opus
