### ISSUE TITLE
workers RAM consumption

### ISSUE THREAD

**Issue by prokopevaleksey** [alumae/kaldi-gstreamer-server#74]
Thank you a lot for this awesome project!

However I have a minor concern about the efficiency of RAM usage for workers. As far as I understood each worker load the model into the memory for itself each time evoked.
  
I am just wondering is there an easy way to load the model into RAM once and make workers share it?

Thank you.

**Comment by alumae** [comment]
No, there is no easy way to do it.

**Comment by Tsaukpaetra** [comment]
On that note, is it possible to use memory-mapped file handling instead of loading into RAM at all (as an option)? Or does performance degrade so much that keeping everything in RAM is mandatory?
