### ISSUE TITLE
Available Decoder in Kaldi

### ISSUE THREAD

**Issue by rahmanadianto** [alumae/kaldi-gstreamer-server#75]
Hi sir,

To be honest, it's hard to find documentation about available decoder which can be used in self.asr = Gst.ElementFactory.make("X"). In this project, you use onlinegmmdecodefaster and kaldinnet2onlinedecoder, if there is more than that? 
I've tried to use available decoder in kaldi but I got "AttributeError: 'NoneType' object has no attribute 'set_property'". Actually, I am interested to use GMM based decoder but with configurable MFCC like in kaldinnet2onlinedecoder.

Thanks.

**Comment by alumae** [comment]
No, there are no more decoders. The onlinegmmdecodefaster and kaldinnet2onlinedecoder are implemented by myself specifically for this project.
