### ISSUE TITLE
Optimizing the decoder

### ISSUE THREAD

**Issue by jin1004** [alumae/kaldi-gstreamer-server#77]
I am currently using the gstreamer server with my nnet3 model. I am only getting the best hypothesis from the decoder currently, but that still takes a few seconds to process. Can you give me some ideas on how to optimize the decoder? Any help will be appreciated.

**Comment by alumae** [comment]
If you need realtime decoding, I recommend to use chain models. It is very easy to get 0.5x realtime decoding speed with them.

**Comment by jin1004** [comment]
I am actually using a chain model currently, and even with that it takes a few seconds to process. I was wondering if there are ways to optimize it further.

**Comment by alumae** [comment]
Maybe your are using client.py and you don't know that it throttles the uploading of the audio file (see the -r parameter), in order to simulate live decoding?

**Comment by alumae** [comment]
Closing as there is no response to my question.
