### ISSUE TITLE
Word-level confidence

### ISSUE THREAD

**Issue by arielvsp** [alumae/kaldi-gstreamer-server#78]
Hi there,
Is that possible to get a word-level confidence in recognition response? If so, how can this be achieved? If not, maybe I can contribute by adding it (but I may need some advice along the way).
Thanks!
Ariel

**Comment by alumae** [comment]
Implemented in gst-kaldi-nnet2-online. Now, word confidence scores can be included with word alignment information in the full results.

**Comment by arielvsp** [comment]
Great, thank you!
