### ISSUE TITLE
Stuck at 'Starting up server'

### ISSUE THREAD

**Issue by ghosthawkone** [alumae/kaldi-gstreamer-server#84]
I cloned kaldi-gstreamer-server from the repo, installed the required dependencies (JSON, YAML, tornado,..).

On issuing 
`python kaldigstserver/master_server.py --port=8500`

I'm stuck with this:
`DEBUG 2017-06-27 15:46:03,949 Starting up server `

Nothing else is displayed. 
Is this normal behavior?

**Comment by alumae** [comment]
This is normal behaviour. You have to also start a worker (in another terminal) which output more info. Read the README.
