### ISSUE TITLE
connection close for non-english (hindi) characters

### ISSUE THREAD

**Issue by rohithkodali** [alumae/kaldi-gstreamer-server#86]
HI,

  with the latest code i have seen a weird issue, I’m testing on a Indian language using nnet-3 chain models, it is working well for English but when it is for utf-8 encoding language (ex: Hindi) the server closes automatically when it received encoded result.

here is the server log

    INFO 2017-07-01 11:28:09,640 New worker available <__main__.WorkerSocketHandler object at 0x7f3e591cd810> 
    INFO 2017-07-01 11:29:24,301 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: OPEN 
    INFO 2017-07-01 11:29:24,301 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: Request arguments: content-type="" 
    INFO 2017-07-01 11:29:24,301 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: Using worker <__main__.DecoderSocketHandler object at 0x7f3e5915e1d0> 
    INFO 2017-07-01 11:29:24,493 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: Forwarding client message (<type 'str'>) of length 8000 to worker 
    INFO 2017-07-01 11:29:24,745 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: Forwarding client message (<type 'str'>) of length 8000 to worker 
    INFO 2017-07-01 11:29:24,998 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: Forwarding client message (<type 'str'>) of length 8000 to worker 
    INFO 2017-07-01 11:29:25,252 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: Forwarding client message (<type 'str'>) of length 8000 to worker 
    INFO 2017-07-01 11:29:25,505 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: Forwarding client message (<type 'str'>) of length 8000 to worker 
    INFO 2017-07-01 11:29:25,624 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: Sending event {u'status': 0, u'segment': 0, u'result': {u'hypotheses': [{u'transcript': u'<s>.'}], u'final': Fa... to client 
    INFO 2017-07-01 11:29:25,758 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: Forwarding client message (<type 'str'>) of length 8000 to worker 
    INFO 2017-07-01 11:29:26,011 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: Forwarding client message (<type 'str'>) of length 8000 to worker 
    INFO 2017-07-01 11:29:26,210 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: Sending event {u'status': 0, u'segment': 0, u'result': {u'hypotheses': [{u'transcript': u'<s> \u0c24\u0c46\u0c3... to client 
    INFO 2017-07-01 11:29:26,215 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: Handling on_connection_close() 
    INFO 2017-07-01 11:29:26,215 bd806fc9-de9d-4d91-8f18-0ed4b0d827f0: Closing worker connection 
    INFO 2017-07-01 11:29:26,220 Worker <__main__.WorkerSocketHandler object at 0x7f3e591cd810> leaving 

on client side it through connection close error

2017-07-01 11:29:05 - WARNING:   __main__: Failed to send event to master: Cannot send on a terminated websocket

any clue of why it happens?

**Comment by cathryn0131** [comment]
hi, I met the same issue, how did you solve it? thanks in advance.

**Comment by taomanwai** [comment]
Same issue too , even for EN, e.g. bill_gates-TED.mp3. Anyone can help?

**Comment by nikosapaster** [comment]
hello I probably have the same issue.
please update this with the solution
