### ISSUE TITLE
decoder.py - Finish request error

### ISSUE THREAD

**Issue by leesherwood** [alumae/kaldi-gstreamer-server#87]
I've noticed that when a worker disconnects due to receiving no data, it isn't sending a message back to my client, nor is it shutting down correctly (which means supervisor doesn't restart it, and I lose one worker permanently from the master, until i manually restart it).

I've traced the issue down too this line:
https://github.com/alumae/kaldi-gstreamer-server/blob/master/kaldigstserver/decoder.py#L158

If I comment that line out, everything works as i'd expect it too.

I can recreate this issue everytime, i have my timeout set too 10 seconds, so i start a webcoket connection to the server, but don't send any data too it. 10 seconds later the worker  starts the cancellation/shutdown process, but the websocket remains open (i can run a WS ping too it and get a successful pong response).

However i'm not a python developer (this is my first time messing with Python) and I don't really understand gstreamer or kaldi (i'm just setting up the servers).

Question 1: Why is this happening?

Question 2: What does that line actually do?

Question 3: Can i safely comment out that line without any adverse effects (the process is shutting down anyway, so presumably it'll all clean itself up anyway?)

Any help would be greatly appreciated :)

**Comment by alumae** [comment]
If I remember correctly, this line was added exactly because otherwise, the worker wouldn't shut down correctly. 

Now, I haven't used the GMM-based decoder for a while, and I believe what you are experiencing is caused by differences between different versions of the GStreamer. To be honest, I don't exactly know what this line is supposed to do, it just seemed to make things work for me in such corner cases. 

So, feel free to comment this line out if it works for you.

**Comment by leesherwood** [comment]
Interesting!

In that case i'll just comment it out and test all the other finish_request scenarios too make sure it doesn't then cause hanging in other circumstances.

Thanks for the swift response alumae

Note: I'm using Gstreamer 1.8.2 (should anyone look at this issue in the future, and commenting it out does indeed resolve the issue).

**Comment by manuelgentile** [comment]
> Interesting!
> 
> In that case i'll just comment it out and test all the other finish_request scenarios too make sure it doesn't then cause hanging in other circumstances.
> 
> Thanks for the swift response alumae
> 
> Note: I'm using Gstreamer 1.8.2 (should anyone look at this issue in the future, and commenting it out does indeed resolve the issue).

Maybe now your link point to the wrong line of code. Could you update? Thanks

**Comment by leesherwood** [comment]
@manuelgentile Unfortunately I don't remember much about the issue , but the line was this one I believe:

https://github.com/alumae/kaldi-gstreamer-server/blob/d8386effbd705bfb9f14411f0d91a6c824026365/kaldigstserver/decoder.py#L158
