### ISSUE TITLE
Decoding nnet3 with gstreamer

### ISSUE THREAD

**Issue by angel101** [alumae/kaldi-gstreamer-server#89]
Hello,

Im having some problems at the time to decode with a nnet3 model, keep getting this error and i really cant get around it. 
 Expected token " < MaxChangePerSample > ", got instead " < IsGradient > ".

i found this https://github.com/kaldi-asr/kaldi/issues/1660
they say that a old code version cant run a model with a newer receipt.

any help its appreciated.

**Comment by alumae** [comment]
Yes, it looks like version incompatibility. Either your model is trained using a too old version of Kaldi, or your Kaldi GStreamer plugin is compiled using an old Kaldi version.
