### ISSUE TITLE
Input feature dimension mismatch

### ISSUE THREAD

**Issue by star633669** [alumae/kaldi-gstreamer-server#91]
Hi
When I send an audio to server I got an error as follow as

ERROR ([5.2.74~1-dbdd]:DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:45) Input feature dimension mismatch: got 40 but network expects 43

where can change the input dimension to 43?
I will appreciate any help

**Comment by alumae** [comment]
Check that your mfcc-config file, as specified in the configuration YAML file, is compatible with your acoustic model.

**Comment by star633669** [comment]
Thank you for your reply.
 in my mfcc-config file as follow as
--use-energy=false
--sample-frequency=16000 
--num-mel-bins=40
--num-ceps=40
--low-freq=40
--high-freq=-200 

which argument I must be modify

**Comment by alumae** [comment]
Sorry, I don't know the specifics of your acoustic model.
