### ISSUE TITLE
Uncaught exception in /client/ws/speech

### ISSUE THREAD

**Issue by 0307lin** [alumae/kaldi-gstreamer-server#94]
hi, i have some problems when i builde my model in kaldi-gstreamer-server
i have two models, another one is ok, but this one has some trouble, how can i go about this problem?
thx：）

_there is an error in my master.log:_
    ERROR 2017-09-18 15:18:04,990 Uncaught exception in /client/ws/speech
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 494, in _run_callback
     result = callback(*args, **kwargs)
   File "kaldigstserver/master_server.py", line 326, in on_message
     self.worker.write_message(message, binary=True)
   File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 249, in write_message
     raise WebSocketClosedError()
 WebSocketClosedError
     INFO 2017-09-18 15:18:05,051 0ae01a87-815e-40f7-be5f-54076acf2d89: Handling on_connection_close()

_there is an error in my worker.log:_
ERROR ([5.2.132~1-82686]:DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:45) Input feature dimension mismatch: got 40 but network expects 43

and my log is there:
my**master.log**

>  DEBUG 2017-09-18 15:15:31,700 Starting up server
>     INFO 2017-09-18 15:16:25,753 101 GET /worker/ws/speech (::1) 50.20ms
>     INFO 2017-09-18 15:16:25,776 New worker available <__main__.WorkerSocketHandler object at 0x7fa72d757fd0>
>     INFO 2017-09-18 15:16:25,778 101 GET /worker/ws/speech (::1) 0.59ms
>     INFO 2017-09-18 15:16:25,778 New worker available <__main__.WorkerSocketHandler object at 0x7fa72d757c50>
>     INFO 2017-09-18 15:18:01,832 101 GET /client/ws/speech?content-type=audio/x-raw,+layout=(string)interleaved,+rate=(int)16000,+format=(string)S16LE,+channels=(int)1 (172.23.12.242) 0.71ms
>     INFO 2017-09-18 15:18:01,856 0ae01a87-815e-40f7-be5f-54076acf2d89: OPEN
>     INFO 2017-09-18 15:18:01,856 0ae01a87-815e-40f7-be5f-54076acf2d89: Request arguments: content-type="audio/x-raw, layout=(string)interleaved, rate=(int)16000, format=(string)S16LE, channels=(int)1"
>     INFO 2017-09-18 15:18:01,856 0ae01a87-815e-40f7-be5f-54076acf2d89: Using worker <__main__.DecoderSocketHandler object at 0x7fa72d773850>
>     INFO 2017-09-18 15:18:01,857 0ae01a87-815e-40f7-be5f-54076acf2d89: Using content type: audio/x-raw, layout=(string)interleaved, rate=(int)16000, format=(string)S16LE, channels=(int)1
>     INFO 2017-09-18 15:18:02,210 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:02,328 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:02,441 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:02,565 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:02,681 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:02,808 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:02,925 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:03,044 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:03,163 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:03,284 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:03,404 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:03,522 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:03,642 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:03,765 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:03,880 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:04,000 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:04,123 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:04,245 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:04,365 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:04,483 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:04,603 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:04,724 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:04,847 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>     INFO 2017-09-18 15:18:04,959 Worker <__main__.WorkerSocketHandler object at 0x7fa72d757fd0> leaving
>     INFO 2017-09-18 15:18:04,967 0ae01a87-815e-40f7-be5f-54076acf2d89: Forwarding client message (<type 'str'>) of length 3840 to worker
>    **ERROR 2017-09-18 15:18:04,990 Uncaught exception in /client/ws/speech**
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 494, in _run_callback
>     result = callback(*args, **kwargs)
>   File "kaldigstserver/master_server.py", line 326, in on_message
>     self.worker.write_message(message, binary=True)
>   File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 249, in write_message
>     raise WebSocketClosedError()
> WebSocketClosedError
>     INFO 2017-09-18 15:18:05,051 0ae01a87-815e-40f7-be5f-54076acf2d89: Handling on_connection_close()
>     INFO 2017-09-18 15:18:05,051 0ae01a87-815e-40f7-be5f-54076acf2d89: Closing worker connection
> 

my **worker.log**:

> kaldionline@cca-train03:~/kaldi-gstreamer-server/log$ vim zlinworker1.log 
> 2017-09-18 15:16:20 -    INFO:   decoder2: Setting decoder property: model = ../zlinonline051/final.mdl
> LOG ([5.2.132~1-82686]:CompileLooped():nnet-compile-looped.cc:336) Spent 0.181958 seconds in looped compilation.
> 2017-09-18 15:16:23 -    INFO:   decoder2: Setting decoder property: chunk-length-in-secs = 0.25
> 2017-09-18 15:16:23 -    INFO:   decoder2: Created GStreamer elements
> 2017-09-18 15:16:23 -   DEBUG:   decoder2: Adding <__main__.GstAppSrc object at 0x7fd4ce1b08c0 (GstAppSrc at 0x234ea20)> to the pipeline
> 2017-09-18 15:16:23 -   DEBUG:   decoder2: Adding <__main__.GstDecodeBin object at 0x7fd4ce1b0aa0 (GstDecodeBin at 0x23480e0)> to the pipeline
> 2017-09-18 15:16:23 -   DEBUG:   decoder2: Adding <__main__.GstAudioConvert object at 0x7fd4ce1b09b0 (GstAudioConvert at 0x236bfa0)> to the pipeline
> 2017-09-18 15:16:23 -   DEBUG:   decoder2: Adding <__main__.GstAudioResample object at 0x7fd4ce1b0960 (GstAudioResample at 0x23798c0)> to the pipeline
> 2017-09-18 15:16:23 -   DEBUG:   decoder2: Adding <__main__.GstTee object at 0x7fd4ce1b0a50 (GstTee at 0x2324aa0)> to the pipeline
> 2017-09-18 15:16:23 -   DEBUG:   decoder2: Adding <__main__.GstQueue object at 0x7fd4ce1b0910 (GstQueue at 0x237e030)> to the pipeline
> 2017-09-18 15:16:23 -   DEBUG:   decoder2: Adding <__main__.GstFileSink object at 0x7fd4ce1b0a00 (GstFileSink at 0x23826d0)> to the pipeline
> 2017-09-18 15:16:23 -   DEBUG:   decoder2: Adding <__main__.GstQueue object at 0x7fd4ce1b0af0 (GstQueue at 0x237e320)> to the pipeline
> 2017-09-18 15:16:23 -   DEBUG:   decoder2: Adding <__main__.Gstkaldinnet2onlinedecoder object at 0x7fd4ce171dc0 (Gstkaldinnet2onlinedecoder at 0x23a6080)> to the pipeline
> 2017-09-18 15:16:23 -   DEBUG:   decoder2: Adding <__main__.GstFakeSink object at 0x7fd4ce171e10 (GstFakeSink at 0x2284e00)> to the pipeline
> 2017-09-18 15:16:23 -    INFO:   decoder2: Linking GStreamer elements
> LOG ([5.2.132~1-82686]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
> LOG ([5.2.132~1-82686]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
> 2017-09-18 15:16:24 -    INFO:   decoder2: Setting pipeline to READY
> 2017-09-18 15:16:24 -    INFO:   decoder2: Set pipeline to READY
> 2017-09-18 15:16:25 -    INFO:   __main__: Opening websocket connection to master server
> 2017-09-18 15:16:25 -    INFO:   __main__: Opened websocket connection to server
> 2017-09-18 15:18:01 -   DEBUG:   __main__: <undefined>: Got message from server of type <class 'ws4py.messaging.TextMessage'>
> 2017-09-18 15:18:01 -    INFO:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Initializing request
> 2017-09-18 15:18:01 -    INFO:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Setting caps to audio/x-raw, layout=(string)interleaved, rate=(int)16000, format=(string)S16LE, channels=(int)1
> 2017-09-18 15:18:01 -    INFO:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Connecting audio decoder
> 2017-09-18 15:18:01 -    INFO:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Connected audio decoder
> 2017-09-18 15:18:01 -    INFO:   __main__: 0ae01a87-815e-40f7-be5f-54076acf2d89: Started timeout guard
> 2017-09-18 15:18:01 -   DEBUG:   __main__: 0ae01a87-815e-40f7-be5f-54076acf2d89: Checking that decoder hasn't been silent for more than 10 seconds
> 2017-09-18 15:18:01 -    INFO:   __main__: 0ae01a87-815e-40f7-be5f-54076acf2d89: Initialized request
> 2017-09-18 15:18:02 -   DEBUG:   __main__: 0ae01a87-815e-40f7-be5f-54076acf2d89: Got message from server of type <class 'ws4py.messaging.BinaryMessage'>
> 2017-09-18 15:18:02 -   DEBUG:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Pushing buffer of size 3840 to pipeline
> 2017-09-18 15:18:02 -   DEBUG:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Pushing buffer done
> 2017-09-18 15:18:02 -   DEBUG:   __main__: 0ae01a87-815e-40f7-be5f-54076acf2d89: Got message from server of type <class 'ws4py.messaging.BinaryMessage'>
> 2017-09-18 15:18:02 -   DEBUG:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Pushing buffer of size 3840 to pipeline
> 2017-09-18 15:18:02 -   DEBUG:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Pushing buffer done
> 2017-09-18 15:18:02 -   DEBUG:   __main__: 0ae01a87-815e-40f7-be5f-54076acf2d89: Got message from server of type <class 'ws4py.messaging.BinaryMessage'>
> 2017-09-18 15:18:02 -   DEBUG:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Pushing buffer of size 3840 to pipeline
> 2017-09-18 15:18:02 -   DEBUG:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Pushing buffer done
> 2017-09-18 15:18:02 -   DEBUG:   __main__: 0ae01a87-815e-40f7-be5f-54076acf2d89: Got message from server of type <class 'ws4py.messaging.BinaryMessage'>
> 2017-09-18 15:18:02 -   DEBUG:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Pushing buffer of size 3840 to pipeline
> 2017-09-18 15:18:02 -   DEBUG:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Pushing buffer done
> 2017-09-18 15:18:02 -   DEBUG:   __main__: 0ae01a87-815e-40f7-be5f-54076acf2d89: Got message from server of type <class 'ws4py.messaging.BinaryMessage'>
> 2017-09-18 15:18:02 -   DEBUG:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Pushing buffer of size 3840 to pipeline
> 2017-09-18 15:18:02 -   DEBUG:   decoder2: 0ae01a87-815e-40f7-be5f-54076acf2d89: Pushing buffer done
> **ERROR ([5.2.132~1-82686]:DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:45) Input feature dimension mismatch: got 40 but network expects 43**
> 
> [ Stack-Trace: ]
> 
> kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
> kaldi::MessageLogger::~MessageLogger()
> kaldi::nnet3::DecodableNnetLoopedOnlineBase::DecodableNnetLoopedOnlineBase(kaldi::nnet3::DecodableNnetSimpleLoopedInfo const&, kaldi::OnlineFeatureInterface*, kaldi::OnlineFeatureInterface*)
> kaldi::nnet3::DecodableAmNnetLoopedOnline::DecodableAmNnetLoopedOnline(kaldi::TransitionModel const&, kaldi::nnet3::DecodableNnetSimpleLoopedInfo const&, kaldi::OnlineFeatureInterface*, kaldi::OnlineFeatureInterface*)
> kaldi::SingleUtteranceNnet3Decoder::SingleUtteranceNnet3Decoder(kaldi::LatticeFasterDecoderConfig const&, kaldi::TransitionModel const&, kaldi::nnet3::DecodableNnetSimpleLoopedInfo const&, fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > const&, kaldi::OnlineNnet2FeaturePipeline*)
>

**Comment by 0307lin** [comment]
@alumae help…
could you please help me to found what's the problem in my model?

**Comment by alumae** [comment]
Could it be that your model that is causing the error uses pitch features? Unfortunately, kaldi-gstreamer-server doesn't support pitch features.

**Comment by 0307lin** [comment]
@alumae  
Yes yes, i used pitch feature in my model 
there is 39 dims about mfcc and 3 dims about pitch  
so this error said got 40 but network expects 43 ?
ERROR ([5.2.132~1-82686]:DecodableNnetLoopedOnlineBase():decodable-online-looped.cc:45) Input feature dimension mismatch: got 40 but network expects 43

oh, so , i can't use kaldi-gstreamer-server in my model which has pitch feature?
that so pity  TT...
Are there any other solutions here? TT
Thank you^_^

**Comment by alumae** [comment]
If you could share your model files (everything that is needed by kaldi-gstreamer-server), I believe it would be very easy to add the support for pitch features. I have never used pitch features myself.

**Comment by 0307lin** [comment]
Wow. yes ,that's sounds good, but this model is not only belongs to me, i need ask my teammate, if it is ok, i will touch with you. 
Thx~ ^_^

**Comment by 0307lin** [comment]
@alumae  we want to do something for kaldi-gstreamer-server ：）so we will share our model files to you, maybe  we need  send an e-mail to your email alumae@gmail.com ?

**Comment by alumae** [comment]
Yes, that's my email

**Comment by alumae** [comment]
To others: kaldi-gstreamer-server *does* support models with pitch features (my statement above was incorrect). Just set the `add-pitch : true` and something like `online-pitch-config : models/xxx/conf/online_pitch.conf` under the `decoder` conf in the YAML file.
