### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by skx300** [alumae/kaldi-gstreamer-server#96]
Hi, 

It seems like that each process has its own acoustic and language model, which they occupy a lot of memory (>3G). If I open 10 processes, then I will need 10 times more memory of the single process. Is there any clue to make these processes **share** the acoustic and language model?

**Comment by alumae** [comment]
No, there are no plans to implement this as it would be quite complicated.

**Comment by skx300** [comment]
Do you have any clue for this direction? I may dig into this hole.

**Comment by alumae** [comment]
Well, you would have to figure out how to share models between different processes. Sorry, but I have no clue how to do this. 
If you use rescoring with a large LM, then it's possible to put the rescoring machinery in a decicated process that is shared by different processes. I know it has been implemented by a third party, but it's not open source, see http://ebooks.iospress.nl/volumearticle/45516
