### ISSUE TITLE
Kaldi decoder don't have lda-mat option?

### ISSUE THREAD

**Issue by luvwinnie** [alumae/kaldi-gstreamer-server#97]
Hi @alumae , I'm trying to use nnet3 models with lda calculated features.
I wondering gstreamer doesn't have lda-mat options? 
In kaldi-gstreamer-server/sample_worker.yaml files , there is a sample which specifies lda-mat options.

When I included lda-mat: lda.mat in my yaml file it shows this error.

`2017-09-29 01:28:07 -    INFO:   decoder2: Setting decoder property: nnet-mode = 3
2017-09-29 01:28:07 -    INFO:   decoder2: Setting decoder property: ivector-extraction-config = /opt/models/conf/ivector_extractor.conf
2017-09-29 01:28:07 -    INFO:   decoder2: Setting decoder property: lattice-beam = 6.0
2017-09-29 01:28:07 -    INFO:   decoder2: Setting decoder property: acoustic-scale = 0.083
2017-09-29 01:28:07 -    INFO:   decoder2: Setting decoder property: lda-mat = /opt/models/conf/lda.mat
Traceback (most recent call last):
  File "/opt/kaldi-gstreamer-server/kaldigstserver/worker.py", line 365, in <module>
    main()
  File "/opt/kaldi-gstreamer-server/kaldigstserver/worker.py", line 345, in main
    decoder_pipeline = DecoderPipeline2(conf)
  File "/opt/kaldi-gstreamer-server/kaldigstserver/decoder2.py", line 24, in __init__
    self.create_pipeline(conf)
  File "/opt/kaldi-gstreamer-server/kaldigstserver/decoder2.py", line 64, in create_pipeline
    self.asr.set_property(key, val)
TypeError: object of type `Gstkaldinnet2onlinedecoder' does not have property `lda-mat'`

How can I use lda features in Kaldi-Gstreamer?

Edited※
In addition , without the lda-mat in yaml file. It almost work but during the recognition phase 
It shows the features dimension is not correct,

`ERROR ([5.2.62~1-a2342]:OnlineTransform():online-feature.cc:421) Dimension mismatch: source features have dimension 117 and LDA #cols is 301

[ Stack-Trace: ]
kaldi::MessageLogger::HandleMessage(kaldi::LogMessageEnvelope const&, char const*)
kaldi::MessageLogger::~MessageLogger()
kaldi::OnlineTransform::OnlineTransform(kaldi::MatrixBase<float> const&, kaldi::OnlineFeatureInterface*)
kaldi::OnlineIvectorFeature::OnlineIvectorFeature(kaldi::OnlineIvectorExtractionInfo const&, kaldi::OnlineFeatureInterface*)
kaldi::OnlineNnet2FeaturePipeline::OnlineNnet2FeaturePipeline(kaldi::OnlineNnet2FeaturePipelineInfo const&)
`
Question:How can I specify the features to be calculated with LDA?

**Comment by alumae** [comment]
With nnet models, the LDA is usually embedded in the model, thus I don't think a separate lda-mat property is supported. In general kaldi-gstreamer-server supports a similar set of properties as Kaldi's online2-wav-nnet3-latgen-faster and online2-wav-nnet2-latgen-faster binaries, which also don't support lda-mat.

**Comment by smolendawid** [comment]
I have got similar problem with Dimension mismatch.

However, I don't understand what solution can I apply. It means that I have to get rid of LDA in my chain model, doesn't it?

**Comment by alumae** [comment]
No, it doesn't mean that.
Are you able to use online2-wav-nnet3-latgen-faster to decode with your model? Probably yes. But online2-wav-nnet3-latgen-faster also doesn't support the lda-mat argument, that's because the LDA matrix is embedded in the chain models and you don't need to specify it. 

Or maybe the model uses *features* that are LDA-transformed? This is not supported, but it's also not supported by Kaldi's  online2-wav-nnet3-latgen-faster.
