### ISSUE TITLE
Problem in client.py and solution (bug related to FileType initialization)

### ISSUE THREAD

**Issue by gruly** [alumae/kaldi-gstreamer-server#98]
When reading an audio file in the following code:
```
            with self.audiofile as audiostream:
                for block in iter(lambda: audiostream.read(self.byterate/4), ""):
                    self.send_data(block)

```
a problem can occur (at least when used under Windows): block don't have a fixed length, and this length is lower than self.byterate/4. As a consequence, the streaming is corrupted and this error message is printed:
>  Received error from server (status 5)
>     Error message : Could not determine type of stream.

This problem can easily be solved by replacing this line:
`    parser.add_argument('audiofile', help="Audio file to be sent to the server", type=argparse.FileType('r'), default=sys.stdin)
`
by this one:
`    parser.add_argument('audiofile', help="Audio file to be sent to the server", type=argparse.FileType('rb'), default=sys.stdin)
`

-> we need to explicit the opening of a **binary** file.

**Comment by alumae** [comment]
Fixed, thanks a lot!

**Comment by gruly** [comment]
You're welcome.
This work is wonderful, thank you for sharing it.
